### ISSUE TITLE
Filestash feature request:  list of share links

### ISSUE THREAD

**Issue by posLop** [mickael-kerjean/filestash-website#29]
it would be extremely helpful if in the filestash ftp veiwer you could see a list of all your share links that you have created in order to manage them easier.  because im probably going to forget about some of them and quick access to them without navigating through all the directorys it would be very useful to access them all from a single sortable list.

**Comment by mickael-kerjean** [comment]
Hey, I don't have time at the moment to work on features nobody are paying for. If you want to work on something, you can either create a PR or become a customer.
Cheers
Mickael
