### ISSUE TITLE
Feature overview typo

### ISSUE THREAD

**Issue by floriama** [mickael-kerjean/filestash-website#3]
The feature overview lists 'Customisation' twice.
Nice project btw!

**Comment by mickael-kerjean** [comment]
Good to see some it's getting used! I'm not sure what you mean, what's wrong?

**Comment by floriama** [comment]
![Screenshot from 2019-03-14 10-44-57](https://user-images.githubusercontent.com/8379378/54346948-3efe0280-4646-11e9-98c9-a729fad86995.png)

'Customisation' is listed twice.

**Comment by mickael-kerjean** [comment]
Done, thank you for the report!
