### ISSUE TITLE
Filestash feature request:  download zip of a folder while viewing inside of the folder

### ISSUE THREAD

**Issue by posLop** [mickael-kerjean/filestash-website#30]
currently in order to download a folder as a zip you have to select it by highlighting it then hitting the download button.  however if i want to share a folder with lots of pictures i want other people to be able to mass download that folder without having access to other folders and files next to it.
for example:
If i have a folder called `pictures` and under that, i have `vacation` and `private` and i want to share the `vacation` folder for download i would have to share the `pictures` folder in order for a download option to appear for the `vacation` folder.  i would like to be able to just share the `vacation` folder and have a download option within it when viewing it.

**Comment by mickael-kerjean** [comment]
Hey, I don't have time at the moment to work on features nobody are paying for. If you want to work on something, you can either create a PR or become a customer.
Cheers
Mickael
