### ISSUE TITLE
cannot build plugins

### ISSUE THREAD

**Issue by higi** [mickael-kerjean/filestash-website#4]
Hey,
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
used: https://github.com/mickael-kerjean/filestash/pull/136/commits/6501582e2bee3bdeccd856173ab3db41afaef19d

this gives me:
mkdir -p ./dist/data/plugin
go build -buildmode=plugin -o ./dist/data/plugin/image.so server/plugin/plg_image_light/index.go

server/plugin/plg_image_light/index.go:122:46: cannot use func literal (type func(io.ReadCloser, *common.App, *http.ResponseWriter, *http.Request) (io.Reader, error)) as type func(io.ReadCloser, *common.App, *http.ResponseWriter, *http.Request) (io.ReadCloser, error) in argument to common.Hooks.Register.ProcessFileContentBeforeSend

anynone can help pls?

**Comment by higi** [comment]
ou wrong section sorry (should be in filestash repo)

**Comment by mickael-kerjean** [comment]
I've recreate the issue in the filestash repo, this repo relates to the website: http://filestash.app
